# Generated by Django 5.1.15 on 2026-07-19 22:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_repairorder_equipments'),
    ]

    operations = [
        # SparePart: изменяем поля resistance, power, voltage, current, capacitance на Decimal + добавляем unit-поля
        migrations.AlterField(
            model_name='sparepart',
            name='resistance',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='Сопротивление'),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='resistance_unit',
            field=models.CharField(blank=True, default='Ом', help_text='Ом, кОм, МОм', max_length=10, verbose_name='Ед. изм. сопротивления'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='power',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='Мощность'),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='power_unit',
            field=models.CharField(blank=True, default='Вт', help_text='Вт, мВт, кВт', max_length=10, verbose_name='Ед. изм. мощности'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='voltage',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='Напряжение'),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='voltage_unit',
            field=models.CharField(blank=True, default='В', help_text='В, кВ, мВ', max_length=10, verbose_name='Ед. изм. напряжения'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='current',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='Ток'),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='current_unit',
            field=models.CharField(blank=True, default='А', help_text='А, мА, мкА', max_length=10, verbose_name='Ед. изм. тока'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='capacitance',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='Ёмкость'),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='capacitance_unit',
            field=models.CharField(blank=True, default='Ф', help_text='Ф, мкФ, нФ, пФ', max_length=10, verbose_name='Ед. изм. ёмкости'),
        ),
        # RepairOrderEquipment: добавляем индивидуальные поля
        migrations.AddField(
            model_name='repairorderequipment',
            name='initial_condition',
            field=models.TextField(blank=True, verbose_name='Начальное состояние'),
        ),
        migrations.AddField(
            model_name='repairorderequipment',
            name='repair_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость ремонта'),
        ),
        migrations.AddField(
            model_name='repairorderequipment',
            name='seal_numbers',
            field=models.CharField(blank=True, max_length=255, verbose_name='Номера пломб'),
        ),
        migrations.AddField(
            model_name='repairorderequipment',
            name='yandex_disk_folder',
            field=models.URLField(blank=True, verbose_name='Папка на Яндекс.Диске'),
        ),
        # RepairOrder: убираем перенесённые поля
        migrations.RemoveField(
            model_name='repairorder',
            name='initial_condition',
        ),
        migrations.RemoveField(
            model_name='repairorder',
            name='repair_cost',
        ),
        migrations.RemoveField(
            model_name='repairorder',
            name='seal_numbers',
        ),
        migrations.RemoveField(
            model_name='repairorder',
            name='yandex_disk_folder',
        ),
    ]




