# Generated by Django 5.1.15 on 2026-07-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sparepart_units_and_roe_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatushistory',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('unpaid', 'Не оплачен'), ('partially_paid', 'Частично оплачен'), ('paid', 'Оплачен')], max_length=20, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(blank=True, choices=[('accepted', 'Принят'), ('diagnostic', 'Диагностика'), ('repair', 'Ремонт'), ('ready_for_shipment', 'Готов к отгрузке'), ('shipped', 'Отгружен')], max_length=20, verbose_name='Статус ремонта'),
        ),
    ]




