# Generated by Django 5.1.15 on 2026-08-11 21:36

from django.db import migrations, models


def fill_normalized(apps, schema_editor):
    """Заполняет нормализованный серийник у уже существующих записей.

    Логика повторяет Equipment.normalize_serial — в миграциях модель
    подменяется исторической версией без методов, поэтому вызвать
    оригинал отсюда нельзя.
    """
    Equipment = apps.get_model('core', 'Equipment')
    to_update = []
    for equipment in Equipment.objects.all().only('id', 'serial_number'):
        equipment.serial_normalized = ''.join(
            ch for ch in (equipment.serial_number or '') if ch.isalnum()
        ).upper()
        to_update.append(equipment)
    if to_update:
        Equipment.objects.bulk_update(to_update, ['serial_normalized'])


def clear_normalized(apps, schema_editor):
    """Откат: поле удаляется вместе с данными, отдельная очистка не нужна."""


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_storagecell_multiple_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='serial_normalized',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=100, verbose_name='Серийный номер (для поиска)'),
        ),
        migrations.RunPython(fill_normalized, clear_normalized),
    ]
