# Generated by Django 5.1.15 on 2026-08-12 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_equipment_serial_normalized"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("order_status", "Смена статуса заказа"),
                            ("low_stock", "Деталь ушла в дефицит"),
                        ],
                        max_length=30,
                        verbose_name="Событие",
                    ),
                ),
                (
                    "recipient",
                    models.EmailField(max_length=254, verbose_name="Получатель"),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="Тема")),
                ("body", models.TextField(verbose_name="Текст")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "В очереди"),
                            ("sent", "Отправлено"),
                            ("failed", "Не удалось"),
                            ("skipped", "Пропущено"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                        verbose_name="Состояние",
                    ),
                ),
                (
                    "attempts",
                    models.IntegerField(default=0, verbose_name="Попыток отправки"),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, verbose_name="Последняя ошибка"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Отправлено"
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="core.sparepart",
                        verbose_name="Деталь",
                    ),
                ),
                (
                    "repair_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="core.repairorder",
                        verbose_name="Заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оповещение",
                "verbose_name_plural": "Оповещения",
                "ordering": ["-created_at"],
            },
        ),
    ]
