# Generated by Django 5.1.15 on 2026-08-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="max_user_id",
            field=models.CharField(blank=True, max_length=32, verbose_name="ID в MAX"),
        ),
        migrations.AddField(
            model_name="notification",
            name="channel",
            field=models.CharField(
                choices=[("email", "Почта"), ("max", "MAX")],
                db_index=True,
                default="email",
                max_length=10,
                verbose_name="Канал",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="recipient",
            field=models.CharField(max_length=254, verbose_name="Получатель"),
        ),
    ]
