# Generated by Django 5.1.15 on 2026-08-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_max_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True, max_length=32, verbose_name="ID в Telegram"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="channel",
            field=models.CharField(
                choices=[("email", "Почта"), ("max", "MAX"), ("telegram", "Telegram")],
                db_index=True,
                default="email",
                max_length=10,
                verbose_name="Канал",
            ),
        ),
    ]
