# Generated by Django 5.1.15 on 2026-08-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_telegram_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="sparepart",
            name="package",
            field=models.CharField(
                blank=True,
                help_text="0805, DIP-8, TO-220, SOT-23 и т.д.",
                max_length=50,
                verbose_name="Тип корпуса",
            ),
        ),
    ]
