# Generated by Django 5.1.15 on 2026-08-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_sparepart_package"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="event",
            field=models.CharField(
                choices=[
                    ("order_status", "Смена статуса заказа"),
                    ("low_stock", "Деталь ушла в дефицит"),
                    ("debt_reminder", "Напоминание об оплате"),
                    ("debt_digest", "Сводка по задолженностям"),
                ],
                max_length=30,
                verbose_name="Событие",
            ),
        ),
    ]
