# Generated by Django 5.1.15 on 2026-08-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="ООО «Название» — как в документах",
                        max_length=255,
                        verbose_name="Полное название",
                    ),
                ),
                (
                    "inn",
                    models.CharField(blank=True, max_length=20, verbose_name="ИНН"),
                ),
                (
                    "kpp",
                    models.CharField(blank=True, max_length=20, verbose_name="КПП"),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=500, verbose_name="Адрес"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Телефон"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "signatory_position",
                    models.CharField(
                        blank=True,
                        default="Директор",
                        max_length=100,
                        verbose_name="Должность подписанта",
                    ),
                ),
                (
                    "signatory_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ФИО подписанта"
                    ),
                ),
            ],
            options={
                "verbose_name": "Реквизиты организации",
                "verbose_name_plural": "Реквизиты организации",
            },
        ),
    ]
