# Generated by Django 5.1.15 on 2026-08-13 09:02

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_repairorderequipment_work_performed"),
    ]

    operations = [
        migrations.AddField(
            model_name="sparepart",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="За штуку. Обновляется сама при приходе с указанной ценой",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Цена закупки, ₽",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Цена за штуку, ₽",
            ),
        ),
    ]
