# Generated by Django 5.1.15 on 2026-08-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_part_prices"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipmentmodel",
            name="kind",
            field=models.CharField(
                blank=True,
                help_text="Родовое название для акта дефектации: «Преобразователь частоты», «Привод дверей». Если оно уже есть в начале названия модели, поле оставьте пустым.",
                max_length=100,
                verbose_name="Тип оборудования",
            ),
        ),
        migrations.AddField(
            model_name="repairorderequipment",
            name="defect_act_date",
            field=models.DateField(
                blank=True,
                help_text="День диагностики. Пусто — в акте встанет сегодняшнее число.",
                null=True,
                verbose_name="Дата акта дефектации",
            ),
        ),
        migrations.AddField(
            model_name="repairorderequipment",
            name="diagnosis",
            field=models.TextField(
                blank=True,
                help_text="Что вышло из строя. Печатается в акте дефектации.",
                verbose_name="Результаты диагностики",
            ),
        ),
        migrations.AddField(
            model_name="repairorderequipment",
            name="error_codes",
            field=models.TextField(
                blank=True,
                help_text="По одному в строке, вместе с расшифровкой: «F2340» — короткое замыкание в IGBT модуле.",
                verbose_name="Коды ошибок",
            ),
        ),
        migrations.AddField(
            model_name="repairorderequipment",
            name="estimated_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Оценка для заказчика по итогам дефектации. Не то же самое, что стоимость ремонта: та ставится по факту.",
                max_digits=12,
                null=True,
                verbose_name="Ориентировочная стоимость ремонта",
            ),
        ),
        migrations.AddField(
            model_name="repairorderequipment",
            name="non_warranty_reason",
            field=models.TextField(
                blank=True,
                help_text="Продолжение фразы «неисправность вызвана …».",
                verbose_name="Причина, по которой случай не гарантийный",
            ),
        ),
        migrations.AddField(
            model_name="repairorderequipment",
            name="warranty_case",
            field=models.CharField(
                blank=True,
                choices=[
                    ("warranty", "Гарантийный"),
                    ("non_warranty", "Не гарантийный"),
                ],
                max_length=20,
                verbose_name="Гарантийный случай",
            ),
        ),
    ]
