# Generated by Django 5.1.15 on 2026-08-13 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_defect_act"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Идентификатор в банке",
                    ),
                ),
                (
                    "operation_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата операции"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Сумма"
                    ),
                ),
                (
                    "purpose",
                    models.TextField(blank=True, verbose_name="Назначение платежа"),
                ),
                (
                    "counterparty",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Плательщик"
                    ),
                ),
                (
                    "counterparty_inn",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=20,
                        verbose_name="ИНН плательщика",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Номер документа"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новое"),
                            ("applied", "Разнесено"),
                            ("skipped", "Не по заказам"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Состояние",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Когда обработано"
                    ),
                ),
                (
                    "loaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Загружено"),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bank_operation",
                        to="core.payment",
                        verbose_name="Созданная оплата",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кем обработано",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поступление из банка",
                "verbose_name_plural": "Поступления из банка",
                "ordering": ["-operation_date", "-id"],
            },
        ),
    ]
