# Generated by Django 5.1.15 on 2026-08-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_bank_operation"),
    ]

    operations = [
        migrations.AddField(
            model_name="repairorder",
            name="tbank_invoice_error",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Последняя ошибка выставления"
            ),
        ),
        migrations.AddField(
            model_name="repairorder",
            name="tbank_invoice_pdf_url",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="Ссылка на PDF счёта"
            ),
        ),
        migrations.AddField(
            model_name="repairorder",
            name="tbank_invoice_sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Счёт выставлен через банк"
            ),
        ),
    ]
