# Generated by Django 5.1.15 on 2026-08-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_tbank_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="address",
            field=models.CharField(blank=True, max_length=500, verbose_name="Адрес"),
        ),
        migrations.AddField(
            model_name="organization",
            name="bank_account",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Расчётный счёт"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="bank_bik",
            field=models.CharField(blank=True, max_length=20, verbose_name="БИК"),
        ),
        migrations.AddField(
            model_name="organization",
            name="bank_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="Банк"),
        ),
        migrations.AddField(
            model_name="organization",
            name="corr_account",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Корреспондентский счёт"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="ogrn",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="ОГРН / ОГРНИП"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="tax_note",
            field=models.CharField(
                blank=True,
                default="Без НДС, применяется УСН",
                help_text="Печатается под итогом коммерческого предложения",
                max_length=255,
                verbose_name="Налоговый режим",
            ),
        ),
        migrations.AddField(
            model_name="repairorder",
            name="quote_date",
            field=models.DateField(
                blank=True,
                help_text="Пусто — в документе встанет сегодняшнее число",
                null=True,
                verbose_name="Дата предложения",
            ),
        ),
        migrations.AddField(
            model_name="repairorder",
            name="quote_delivery_terms",
            field=models.CharField(
                blank=True,
                default="до склада Покупателя включена в Предложение",
                max_length=255,
                verbose_name="Условия доставки",
            ),
        ),
        migrations.AddField(
            model_name="repairorder",
            name="quote_lead_time",
            field=models.CharField(
                blank=True,
                default="3-14",
                help_text="Ставится в каждой строке предложения: «3-14»",
                max_length=50,
                verbose_name="Сроки выполнения, дней",
            ),
        ),
        migrations.AddField(
            model_name="repairorder",
            name="quote_payment_terms",
            field=models.CharField(
                blank=True,
                default="100% предоплата покупателем",
                max_length=255,
                verbose_name="Условия оплаты",
            ),
        ),
        migrations.AddField(
            model_name="repairorder",
            name="quote_subject",
            field=models.CharField(
                blank=True,
                help_text="Продолжение заголовка: «на ремонт приводов дверей EkoDrive-2.3-1.3»",
                max_length=255,
                verbose_name="Предмет предложения",
            ),
        ),
        migrations.AddField(
            model_name="repairorder",
            name="quote_valid_until",
            field=models.DateField(
                blank=True, null=True, verbose_name="Действительно до"
            ),
        ),
        migrations.AddField(
            model_name="repairorderequipment",
            name="proposed_work",
            field=models.TextField(
                blank=True,
                help_text="Что предлагаем сделать. Идёт в коммерческое предложение.",
                verbose_name="Предлагаемые работы",
            ),
        ),
        migrations.AddField(
            model_name="repairorderequipment",
            name="repair_complexity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("simple", "Простой"),
                    ("medium", "Средний"),
                    ("complex", "Сложный"),
                ],
                max_length=20,
                verbose_name="Сложность ремонта",
            ),
        ),
    ]
