# Generated by Django 5.1.15 on 2026-08-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_quote"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="city",
            field=models.CharField(
                blank=True,
                default="Москва",
                help_text="Печатается слева от даты в коммерческом предложении",
                max_length=100,
                verbose_name="Город подписания",
            ),
        ),
    ]
