# Generated by Django 5.1.15 on 2026-08-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_spare_part_application"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderstatushistory",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("accepted", "Принят"),
                    ("diagnostic", "Диагностика"),
                    ("repair", "Ремонт"),
                    ("ready_for_shipment", "Готов к отгрузке"),
                    ("shipped", "Отгружен"),
                    ("unrepairable", "Ремонт невозможен"),
                ],
                max_length=20,
                verbose_name="Статус ремонта",
            ),
        ),
        migrations.AlterField(
            model_name="repairorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("accepted", "Принят"),
                    ("diagnostic", "Диагностика"),
                    ("repair", "Ремонт"),
                    ("ready_for_shipment", "Готов к отгрузке"),
                    ("shipped", "Отгружен"),
                    ("unrepairable", "Ремонт невозможен"),
                ],
                default="accepted",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
