# Generated by Django 5.1.15 on 2026-08-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_alter_orderstatushistory_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="notify_by_email",
            field=models.BooleanField(default=True, verbose_name="Оповещения на почту"),
        ),
        migrations.AddField(
            model_name="employee",
            name="notify_by_max",
            field=models.BooleanField(default=True, verbose_name="Оповещения в MAX"),
        ),
        migrations.AddField(
            model_name="employee",
            name="notify_by_telegram",
            field=models.BooleanField(
                default=True, verbose_name="Оповещения в Telegram"
            ),
        ),
    ]
