# Generated by Django 5.1.15 on 2026-08-18 10:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_alter_notification_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("parts", "Детали"),
                            ("labor", "Труд"),
                            ("overhead", "Накладные расходы"),
                        ],
                        max_length=20,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Сумма, ₽",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "repair_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="costs",
                        to="core.repairorder",
                        verbose_name="Заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Затрата по заказу",
                "verbose_name_plural": "Затраты по заказу",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Списано из партии",
                    ),
                ),
                (
                    "incoming",
                    models.ForeignKey(
                        limit_choices_to={"movement_type": "incoming"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batch_allocations",
                        to="core.stockmovement",
                        verbose_name="Партия прихода",
                    ),
                ),
                (
                    "outgoing",
                    models.ForeignKey(
                        limit_choices_to={"movement_type": "outgoing"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="core.stockmovement",
                        verbose_name="Расход",
                    ),
                ),
            ],
            options={
                "verbose_name": "Распределение расхода по партии",
                "verbose_name_plural": "Распределения расхода по партиям",
                "ordering": ["incoming__movement_date"],
            },
        ),
    ]
