# Generated by Django 5.1.15 on 2026-08-18 13:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_ordercost_stockallocation"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventorySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "В процессе"),
                            ("completed", "Завершена"),
                        ],
                        db_index=True,
                        default="in_progress",
                        max_length=15,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Начата"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Завершена"
                    ),
                ),
                (
                    "cabinet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_sessions",
                        to="core.cabinet",
                        verbose_name="Кассетница",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_sessions_completed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кем завершена",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_sessions_started",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кем начата",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сессия инвентаризации",
                "verbose_name_plural": "Сессии инвентаризации",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="InventorySessionLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expected_quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Учтено на начало сессии",
                    ),
                ),
                (
                    "counted_quantity",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Посчитано фактически",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Комментарий при избытке",
                    ),
                ),
                (
                    "cell",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_lines",
                        to="core.storagecell",
                        verbose_name="Ячейка",
                    ),
                ),
                (
                    "movement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_lines",
                        to="core.stockmovement",
                        verbose_name="Движение склада",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_lines",
                        to="core.sparepart",
                        verbose_name="Деталь",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="core.inventorysession",
                        verbose_name="Сессия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Строка инвентаризации",
                "verbose_name_plural": "Строки инвентаризации",
                "ordering": ["cell__row_number", "cell__cell_row", "part__part_number"],
            },
        ),
    ]
