# Generated by Django 5.1.15 on 2026-08-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_inventorysession_inventorysessionline"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="last_seen",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Последняя активность",
            ),
        ),
    ]
