# Generated by Django 5.1.15 on 2026-08-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_invoice_providers"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("tbank", "Т-Банк"), ("tochka", "Точка Банк")],
                        db_index=True,
                        max_length=20,
                        verbose_name="Банк",
                    ),
                ),
                (
                    "event_id",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Событие у банка"
                    ),
                ),
                (
                    "dedup_key",
                    models.CharField(max_length=200, verbose_name="Ключ доставки"),
                ),
                (
                    "body_hash",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="Хеш тела"
                    ),
                ),
                ("body", models.TextField(blank=True, verbose_name="Тело запроса")),
                (
                    "received_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Получено"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Разобрано"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Принято"),
                            ("processed", "Разобрано"),
                            ("failed", "Разобрать не удалось"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=10,
                        verbose_name="Состояние",
                    ),
                ),
                ("result", models.TextField(blank=True, verbose_name="Итог")),
            ],
            options={
                "verbose_name": "Уведомление банка",
                "verbose_name_plural": "Уведомления банков",
                "ordering": ["-received_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "dedup_key"), name="unique_webhook_delivery"
                    )
                ],
            },
        ),
    ]
