# Generated by Django 5.1.15 on 2026-08-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_webhook_delivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="repairorder",
            name="invoice_paid_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Банк сообщил об оплате счёта"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="event",
            field=models.CharField(
                choices=[
                    ("order_status", "Смена статуса заказа"),
                    ("low_stock", "Деталь ушла в дефицит"),
                    ("debt_reminder", "Напоминание об оплате"),
                    ("debt_digest", "Сводка по задолженностям"),
                    ("order_overdue", "Заказ завис в статусе"),
                    ("invoice_paid", "Банк сообщил об оплате счёта"),
                ],
                max_length=30,
                verbose_name="Событие",
            ),
        ),
        migrations.AlterField(
            model_name="webhookdelivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "Принято"),
                    ("processed", "Разобрано"),
                    ("unmatched", "Счёт не найден"),
                    ("failed", "Разобрать не удалось"),
                ],
                db_index=True,
                default="received",
                max_length=10,
                verbose_name="Состояние",
            ),
        ),
    ]
