# Generated by Django 5.1.15 on 2026-08-19 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_invoice_paid_notice"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название типа"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Тип оборудования",
                "verbose_name_plural": "Типы оборудования",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="equipment",
            name="manufacture_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата изготовления"
            ),
        ),
        migrations.AddField(
            model_name="faulttype",
            name="complexity",
            field=models.CharField(
                choices=[("simple", "Простой"), ("complex", "Сложный")],
                default="simple",
                max_length=20,
                verbose_name="Сложность ремонта",
            ),
        ),
        migrations.AlterField(
            model_name="equipmentmodel",
            name="kind",
            field=models.CharField(
                blank=True,
                help_text="Приставка к названию модели в акте дефектации: «Преобразователь частоты», «Привод дверей». Если она уже есть в начале названия модели, поле оставьте пустым. Это не тип из справочника: тип в документы не идёт.",
                max_length=100,
                verbose_name="Родовое название для акта",
            ),
        ),
        migrations.AlterField(
            model_name="faulttype",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Полная формулировка, которая печатается в акте дефектации и в коммерческом предложении. Пусто — неисправность в документы не попадёт вовсе: короткое название вместо описания не подставляется.",
                verbose_name="Описание для документов",
            ),
        ),
        migrations.AlterField(
            model_name="faulttype",
            name="name",
            field=models.CharField(
                help_text="Коротко и по-рабочему, для списков. В документы это название не попадает.",
                max_length=255,
                verbose_name="Неисправность",
            ),
        ),
        migrations.AddField(
            model_name="equipmentmodel",
            name="equipment_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Необязательно. По типу позже подбирается цена из прайса заказчика.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="models",
                to="core.equipmenttype",
                verbose_name="Тип оборудования",
            ),
        ),
        migrations.CreateModel(
            name="EquipmentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Обозначение так, как оно написано на изделии: «1.1», «0.7».",
                        max_length=100,
                        verbose_name="Версия",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Чем эта версия отличается: алюминиевый корпус, большие кнопки. Справочно, в документы не идёт.",
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "equipment_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="core.equipmentmodel",
                        verbose_name="Модель оборудования",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия модели",
                "verbose_name_plural": "Версии моделей",
                "ordering": ["equipment_model__name", "name"],
            },
        ),
        migrations.AddField(
            model_name="equipment",
            name="version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipments",
                to="core.equipmentversion",
                verbose_name="Версия",
            ),
        ),
        migrations.AddField(
            model_name="faulttypepart",
            name="version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fault_type_parts",
                to="core.equipmentversion",
                verbose_name="Только для версии",
            ),
        ),
        migrations.AddConstraint(
            model_name="equipmentversion",
            constraint=models.UniqueConstraint(
                fields=("equipment_model", "name"), name="unique_version_per_model"
            ),
        ),
    ]
