# Generated by Django 5.1.15 on 2026-08-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_equipment_type_version_fault_complexity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipmentversion",
            name="name",
            field=models.CharField(
                help_text="Приписка к названию модели вместе с разделителем — так, как она дописана на изделии: «.4» для БУАД-7-31.4, «-1.1» для EcoDrive-2.3-1.1. Разделитель хранится здесь же: на изделиях он произвольный, правилом его не вывести.",
                max_length=100,
                verbose_name="Версия",
            ),
        ),
    ]
