# Generated by Django 5.1.15 on 2026-08-24 13:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_alter_equipmentversion_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Примечание")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Изменён"),
                ),
                (
                    "client",
                    models.OneToOneField(
                        blank=True,
                        help_text="Пусто — это базовый прайс, один на всю программу.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_list",
                        to="core.client",
                        verbose_name="Заказчик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прайс",
                "verbose_name_plural": "Прайсы",
                "ordering": ["client__name"],
            },
        ),
        migrations.CreateModel(
            name="PriceListLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "complexity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("simple", "Простой"),
                            ("medium", "Средний"),
                            ("complex", "Сложный"),
                        ],
                        help_text="Пусто — цена на любой ремонт этого типа.",
                        max_length=20,
                        verbose_name="Сложность",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "equipment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_lines",
                        to="core.equipmenttype",
                        verbose_name="Тип оборудования",
                    ),
                ),
                (
                    "price_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="core.pricelist",
                        verbose_name="Прайс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Строка прайса",
                "verbose_name_plural": "Строки прайса",
                "ordering": ["equipment_type__name", "complexity"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("price_list", "equipment_type", "complexity"),
                        name="unique_price_per_type_and_complexity",
                    )
                ],
            },
        ),
    ]
