# Generated by Django 5.1.15 on 2026-08-24 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_repairorderdetail_is_planned"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("scheme", "Схема"),
                            ("manual", "Инструкция"),
                            ("method", "Методика проверки"),
                            ("other", "Прочее"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Что это",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("url", models.URLField(max_length=500, verbose_name="Ссылка")),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Примечание"
                    ),
                ),
                (
                    "equipment_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="core.equipmentmodel",
                        verbose_name="Модель оборудования",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="core.equipmentversion",
                        verbose_name="Только для исполнения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Материал по модели",
                "verbose_name_plural": "Материалы по моделям",
                "ordering": [
                    models.Case(
                        models.When(kind="scheme", then=models.Value(0)),
                        models.When(kind="manual", then=models.Value(1)),
                        models.When(kind="method", then=models.Value(2)),
                        models.When(kind="other", then=models.Value(3)),
                        default=models.Value(4),
                        output_field=models.IntegerField(),
                    ),
                    "title",
                ],
            },
        ),
    ]
