# Generated by Django 5.1.15 on 2026-08-25 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_equipmentmaterial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название карты"),
                ),
                (
                    "purpose",
                    models.TextField(
                        blank=True,
                        help_text="Одна-две строки: когда эту карту берут в руки.",
                        verbose_name="Для чего",
                    ),
                ),
                (
                    "equipment_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tech_cards",
                        to="core.equipmentmodel",
                        verbose_name="Модель оборудования",
                    ),
                ),
                (
                    "fault_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Необязательно. Пусто — общая процедура по модели: «как разобрать корпус», «как проверить на стенде».",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tech_cards",
                        to="core.faulttype",
                        verbose_name="Неисправность",
                    ),
                ),
            ],
            options={
                "verbose_name": "Технологическая карта",
                "verbose_name_plural": "Технологические карты",
                "ordering": [
                    models.OrderBy(models.F("fault_type"), nulls_first=True),
                    "title",
                ],
            },
        ),
        migrations.CreateModel(
            name="TechCardStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(default=1, verbose_name="Номер шага"),
                ),
                ("text", models.TextField(verbose_name="Что делать")),
                (
                    "caution",
                    models.CharField(
                        blank=True,
                        help_text="То, что нельзя пропустить: «сначала разрядить конденсаторы». Печатается заметно.",
                        max_length=255,
                        verbose_name="Предостережение",
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="core.techcard",
                        verbose_name="Карта",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tech_card_steps",
                        to="core.equipmentversion",
                        verbose_name="Только для исполнения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаг технологической карты",
                "verbose_name_plural": "Шаги технологических карт",
                "ordering": ["number", "pk"],
            },
        ),
    ]
