# Generated by Django 5.1.15 on 2026-08-25 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_techcard_techcardstep"),
    ]

    operations = [
        migrations.AddField(
            model_name="techcardstep",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Как это выглядит на столе. Снимок уменьшается сам.",
                upload_to="tech_cards/%Y/%m/",
                verbose_name="Снимок",
            ),
        ),
    ]
