# Generated by Django 5.1.15 on 2026-08-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_alter_repairorderequipment_defect_act_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="faulttype",
            name="work_description",
            field=models.TextField(
                blank=True,
                help_text="Что делают, чтобы это устранить: «Заменены электролитические конденсаторы в цепи питания». Подставляется кнопкой в заказе, в поле выполненных работ.",
                verbose_name="Типовые выполненные работы",
            ),
        ),
    ]
