# Generated by Django 5.1.15 on 2026-08-31 12:42

from django.db import migrations, models


def medium_becomes_complex(apps, schema_editor):
    """«Средний» ремонт не бывает — то же решение владельца, что и в
    0047 для единицы оборудования. Занизить сложность значит занизить
    цену по прайсу, а завысить — всего лишь попросить перечитать."""
    PriceListLine = apps.get_model('core', 'PriceListLine')
    PriceListLine.objects.filter(complexity='medium').update(complexity='complex')


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_settingchange"),
    ]

    operations = [
        migrations.RunPython(medium_becomes_complex, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="pricelistline",
            name="complexity",
            field=models.CharField(
                blank=True,
                choices=[("simple", "Простой"), ("complex", "Сложный")],
                help_text="Пусто — цена на любой ремонт этого типа.",
                max_length=20,
                verbose_name="Сложность",
            ),
        ),
    ]
