# Generated by Django 5.1.15 on 2026-09-01 03:55
"""
Четыре зашитые в код роли становятся обычными записями справочника
должностей — с v2.98.0.

Перенос обязан быть **тождественным**: у каждого сотрудника после
миграции ровно тот доступ, что был до неё. Поэтому набор прав каждой
заводской должности повторяет то, что до сих пор было записано
в декораторах `role_required`, в шаблонах и в списках получателей
оповещений, — и ничего сверх того.

Сотрудник с ролью, которой в списке нет (в базе разработчика такие
встречались — `role` был обычной строкой и значения не проверялись),
остаётся без должности: это «доступ как у всех», то есть ровно то,
что у него и было — ни одна страница по такой роли не открывалась.
"""


import django.db.models.deletion
from django.db import migrations, models


# Права заводских должностей — слепок того, что было зашито в коде
# до v2.98.0. Список правится только вместе с самим переносом:
# «Администратор» стоит отдельно, у него полный доступ флагом.
FACTORY_POSITIONS = {
    'admin': ('Администратор', True, ()),
    'warehouse': ('Кладовщик', False, (
        'catalog_delete', 'parts_delete', 'cabinets_manage', 'notify_low_stock',
    )),
    'repair_manager': ('Менеджер по ремонту', False, (
        'orders_delete', 'clients_delete', 'catalog_delete',
        'payment_status_change', 'notify_overdue',
    )),
    'accountant': ('Бухгалтер', False, (
        'payments_manage', 'payment_status_change', 'invoices_send',
        'bank_statement', 'reports_profit', 'notify_debts',
    )),
}


def roles_become_positions(apps, schema_editor):
    Position = apps.get_model('core', 'Position')
    PositionPermission = apps.get_model('core', 'PositionPermission')
    Employee = apps.get_model('core', 'Employee')

    # Заводим все четыре, а не только занятые: это стартовый набор
    # программы, как ячейки у `init_cells`. На свежей установке иначе
    # пришлось бы собирать «Кладовщика» галочками вручную, а на рабочей
    # разница не видна — там эти роли и так у кого-то стоят.
    positions = {}
    for role, (name, is_admin, codes) in FACTORY_POSITIONS.items():
        position, _ = Position.objects.get_or_create(
            name=name, defaults={'is_admin': is_admin}
        )
        positions[role] = position
        for code in codes:
            PositionPermission.objects.get_or_create(position=position, code=code)

    for role, position in positions.items():
        Employee.objects.filter(role=role).update(position=position)


def positions_become_roles(apps, schema_editor):
    """Обратный ход: должность снова становится ролью.

    Заводскую узнаём по названию — своей должности соответствующей роли
    нет, и такой сотрудник откатывается в «менеджера по ремонту», как
    и было умолчанием у поля.
    """
    Employee = apps.get_model('core', 'Employee')
    by_name = {name: role for role, (name, _, _) in FACTORY_POSITIONS.items()}
    for employee in Employee.objects.select_related('position'):
        name = employee.position.name if employee.position_id else ''
        employee.role = by_name.get(name, 'repair_manager')
        employee.save(update_fields=['role'])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_repairer_contacts_status_versions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "is_admin",
                    models.BooleanField(
                        default=False,
                        help_text="Все права, включая те, что появятся в будущих версиях.",
                        verbose_name="Полный доступ",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="Для своих: чем эта должность отличается от соседней.",
                        max_length=255,
                        verbose_name="Примечание",
                    ),
                ),
            ],
            options={
                "verbose_name": "Должность",
                "verbose_name_plural": "Должности",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="core.position",
                verbose_name="Должность",
            ),
        ),
        migrations.CreateModel(
            name="PositionPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("orders_delete", "Удалять заказы"),
                            ("clients_delete", "Удалять заказчиков"),
                            (
                                "catalog_delete",
                                "Удалять записи справочников оборудования",
                            ),
                            ("parts_delete", "Удалять радиодетали"),
                            ("cabinets_manage", "Заводить и править кассетницы"),
                            ("payments_manage", "Вносить и удалять оплаты"),
                            ("payment_status_change", "Менять статус оплаты заказа"),
                            ("invoices_send", "Выставлять счета"),
                            (
                                "bank_statement",
                                "Видеть выписку банка и разносить поступления",
                            ),
                            ("reports_profit", "Отчёт о прибыли"),
                            (
                                "reports_all_engineers",
                                "Аналитика по всем инженерам, а не только своя",
                            ),
                            (
                                "admin_access",
                                "Администрирование: пользователи, должности, настройки, обновление, реквизиты",
                            ),
                            ("notify_low_stock", "Оповещения о дефиците деталей"),
                            ("notify_debts", "Оповещения о долгах заказчиков"),
                            ("notify_overdue", "Оповещения о зависших заказах"),
                        ],
                        max_length=50,
                        verbose_name="Право",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="core.position",
                        verbose_name="Должность",
                    ),
                ),
            ],
            options={
                "verbose_name": "Право должности",
                "verbose_name_plural": "Права должности",
                "ordering": ["code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("position", "code"),
                        name="unique_permission_per_position",
                    )
                ],
            },
        ),
        migrations.RunPython(roles_become_positions, positions_become_roles),
        migrations.RemoveField(
            model_name="employee",
            name="role",
        ),
    ]
