# Generated by Django 5.1.15 on 2026-09-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_positions_replace_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="event",
            field=models.CharField(
                choices=[
                    ("order_status", "Смена статуса заказа"),
                    ("low_stock", "Деталь ушла в дефицит"),
                    ("debt_reminder", "Напоминание об оплате"),
                    ("debt_digest", "Сводка по задолженностям"),
                    ("order_overdue", "Заказ завис в статусе"),
                    ("invoice_paid", "Банк сообщил об оплате счёта"),
                    ("new_payment", "Новое поступление из выписки"),
                ],
                max_length=30,
                verbose_name="Событие",
            ),
        ),
        migrations.AlterField(
            model_name="positionpermission",
            name="code",
            field=models.CharField(
                choices=[
                    ("orders_delete", "Удалять заказы"),
                    ("clients_delete", "Удалять заказчиков"),
                    ("catalog_delete", "Удалять записи справочников оборудования"),
                    ("parts_delete", "Удалять радиодетали"),
                    ("cabinets_manage", "Заводить и править кассетницы"),
                    ("payments_manage", "Вносить и удалять оплаты"),
                    ("payment_status_change", "Менять статус оплаты заказа"),
                    ("invoices_send", "Выставлять счета"),
                    ("bank_statement", "Видеть выписку банка и разносить поступления"),
                    ("reports_profit", "Отчёт о прибыли"),
                    (
                        "reports_all_engineers",
                        "Аналитика по всем инженерам, а не только своя",
                    ),
                    (
                        "admin_access",
                        "Администрирование: пользователи, должности, настройки, обновление, реквизиты",
                    ),
                    ("notify_low_stock", "Оповещения о дефиците деталей"),
                    ("notify_debts", "Оповещения о долгах заказчиков"),
                    ("notify_overdue", "Оповещения о зависших заказах"),
                    ("notify_payments", "Оповещения о новых поступлениях из выписки"),
                ],
                max_length=50,
                verbose_name="Право",
            ),
        ),
    ]
