# Generated by Django 5.1.15 on 2026-09-04 04:25
#
# Точка научилась читать выписку в v2.108.0 — до этого банк, приславший
# поступление, был только один, и различать было не с чем. Строки,
# загруженные раньше, помечаются 'tbank' здесь же: это не догадка,
# а факт — второго источника тогда не существовало.

from django.db import migrations, models


def mark_existing_rows_as_tbank(apps, schema_editor):
    BankOperation = apps.get_model("core", "BankOperation")
    BankOperation.objects.filter(source="").update(source="tbank")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_alter_notification_event_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankoperation",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[("tbank", "Т-Банк"), ("tochka", "Точка Банк")],
                max_length=20,
                verbose_name="Банк",
            ),
        ),
        migrations.AlterField(
            model_name="bankoperation",
            name="external_id",
            field=models.CharField(
                max_length=100, verbose_name="Идентификатор в банке"
            ),
        ),
        migrations.RunPython(mark_existing_rows_as_tbank, noop),
        migrations.AlterUniqueTogether(
            name="bankoperation",
            unique_together={("source", "external_id")},
        ),
    ]
