# Generated by Django 5.1.15 on 2026-09-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_bank_operation_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="diadoc_fns_participant_id",
            field=models.CharField(
                blank=True,
                help_text="Для формирования УПД. Узнаётся через GetCounteragents после того, как заказчик примет приглашение в Диадоке.",
                max_length=100,
                verbose_name="Идентификатор участника ЭДО (Диадок)",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="diadoc_fns_participant_id",
            field=models.CharField(
                blank=True,
                help_text="Для формирования УПД. Узнаётся через GetMyOrganizations в личном кабинете интегратора Диадока, вручную не придумывается.",
                max_length=100,
                verbose_name="Идентификатор участника ЭДО (Диадок)",
            ),
        ),
    ]
