# Generated by Django 5.1.15 on 2026-09-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_diadoc_fns_participant_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="invoice_show_work_performed",
            field=models.BooleanField(
                default=True,
                help_text="Выключить, если этому заказчику в счёте нужно только название ремонта, без перечня выполненных работ.",
                verbose_name="Показывать выполненные работы в счёте",
            ),
        ),
    ]
