# Generated by Django 5.1.15 on 2026-09-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_client_invoice_show_work_performed"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pricelistline",
            options={
                "ordering": ["equipment_type__name", "power_from", "complexity"],
                "verbose_name": "Строка прайса",
                "verbose_name_plural": "Строки прайса",
            },
        ),
        migrations.RemoveConstraint(
            model_name="pricelistline",
            name="unique_price_per_type_and_complexity",
        ),
        migrations.AddField(
            model_name="equipmentversion",
            name="power_kw",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Только там, где от неё зависит цена ремонта (обычно у преобразователей частоты) — розыск цены в прайсе учитывает её. Пусто — цена этой версии от мощности не зависит.",
                max_digits=7,
                null=True,
                verbose_name="Мощность, кВт",
            ),
        ),
        migrations.AddField(
            model_name="pricelistline",
            name="power_from",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=7,
                null=True,
                verbose_name="Мощность от, кВт",
            ),
        ),
        migrations.AddField(
            model_name="pricelistline",
            name="power_to",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Обе границы пустые — цена на любую мощность этого типа. Сравнивается с EquipmentVersion.power_kw единицы.",
                max_digits=7,
                null=True,
                verbose_name="Мощность до, кВт",
            ),
        ),
        migrations.AddConstraint(
            model_name="pricelistline",
            constraint=models.UniqueConstraint(
                fields=(
                    "price_list",
                    "equipment_type",
                    "power_from",
                    "power_to",
                    "complexity",
                ),
                name="unique_price_per_type_power_and_complexity",
            ),
        ),
    ]
