# Generated by Django 5.1.15 on 2026-09-05 05:26
#
# Имя файла не переименовано, хотя операция внутри — уже не та, что была:
# под этим именем миграция уже применена на рабочем Pi (v2.111.0 ошибочно
# убрала RepairOrderEquipment.diagnosis, а не error_codes, см. CLAUDE.md).
# Джанго узнаёт применённую миграцию по имени, а не по содержимому файла,
# и на Pi этот файл больше никогда не выполнится — что бы в нём ни было
# написано. Поэтому здесь оставлено то, что нужно **новым и ещё
# не мигрированным** базам (эта операция, RemoveField error_codes, для
# них верна и безопасна), а фактическое исправление уже мигрировавшей
# базы (Pi) сделано отдельными, ранее не встречавшимися миграциями
# 0059/0060 — они не в списке применённых на Pi и потому выполнятся там
# по-настоящему.
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_power_pricing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repairorderequipment",
            name="error_codes",
        ),
    ]
