# Generated by Django 5.1.15 on 2026-09-05 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_power_pricing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repairorderequipment",
            name="diagnosis",
        ),
    ]
