# Generated by Django 5.1.15 on 2026-09-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0060_drop_error_codes_if_present"),
    ]

    operations = [
        migrations.AddField(
            model_name="sparepart",
            name="datasheet",
            field=models.FileField(
                blank=True,
                help_text="PDF с сайта производителя или дистрибьютора.",
                upload_to="datasheets/%Y/%m/",
                verbose_name="Даташит",
            ),
        ),
    ]
